return {
    ClassicBattlegrounds = {
        loop1 = { 
            Vector3.new(916.665, 78.000, 1309.744), 
            Vector3.new(894.981, 79.000, 1311.221), 
            Vector3.new(883.387, 78.014, 1290.221), 
            Vector3.new(884.815, 98.000, 1264.437), 
            Vector3.new(885.094, 78.000, 1257.697), 
            Vector3.new(915.267, 78.000, 1261.384) 
        },   
        loop2 = {
            Vector3.new(927.136, 94.000, 1444.720), 
            Vector3.new(935.056, 94.000, 1464.585), 
            Vector3.new(941.415, 94.000, 1481.857), 
            Vector3.new(925.230, 94.000, 1483.691), 
            Vector3.new(924.042, 94.000, 1464.236) 
        }, 
        loop3 = { 
            Vector3.new(736.330, 78.000, 1282.137), 
            Vector3.new(732.989, 78.000, 1255.645), 
            Vector3.new(750.899, 78.000, 1241.237), 
            Vector3.new(783.791, 78.000, 1226.762), 
            Vector3.new(762.703, 81.000, 1258.174) 
        },
        barriers = {
            [1] = { 
                Size = Vector3.new(2.00, 5.00, 51.04), 
                Position = Vector3.new(826.15, 77.25, 1247.08), 
                Rotation = Vector3.new(-0.11, -63.04, 0.00) 
            },
            [2] = { 
                Size = Vector3.new(2.00, 5.00, 11.85), 
                Position = Vector3.new(803.85, 76.18, 1222.69), 
                Rotation = Vector3.new(-1.74, -14.45, 0.00) 
            },
            [3] = { 
                Size = Vector3.new(2.00, 5.00, 52.37), 
                Position = Vector3.new(826.12, 76.75, 1263.39), 
                Rotation = Vector3.new(1.63, -60.56, 0.00) 
            },
            [4] = { 
                Size = Vector3.new(2.00, 10.00, 25.78), 
                Position = Vector3.new(803.83, 76.27, 1359.81), 
                Rotation = Vector3.new(1.20, -177.86, 0.00) 
            },
            [5] = { 
                Size = Vector3.new(2.00, 10.00, 17.16), 
                Position = Vector3.new(825.64, 76.00, 1330.17), 
                Rotation = Vector3.new(0.00, 89.94, 0.00) 
            },
            [6] = { 
                Size = Vector3.new(2.00, 10.00, 22.74), 
                Position = Vector3.new(850.03, 76.00, 1355.38), 
                Rotation = Vector3.new(0.00, 175.68, 0.00) 
            },
        }
    },
    BloodfellManor = { 
        loop1 = { 
            Vector3.new(357.468, 16.500, 666.224), 
            Vector3.new(351.751, 16.500, 647.747), 
            Vector3.new(350.780, 16.641, 625.119), 
            Vector3.new(352.426, 16.500, 602.552), 
            Vector3.new(357.500, 16.500, 585.243), 
            Vector3.new(366.239, 16.500, 603.499), 
            Vector3.new(367.278, 16.500, 626.461), 
            Vector3.new(366.345, 16.500, 648.817) 
        }, 
        loop2 = { 
            Vector3.new(472.638, 16.500, 701.118), 
            Vector3.new(489.288, 16.500, 709.232), 
            Vector3.new(506.795, 16.498, 701.859), 
            Vector3.new(495.853, 16.489, 689.182) 
        }, 
        loop3 = { 
            Vector3.new(463.290, 16.500, 550.369), 
            Vector3.new(479.539, 17.177, 536.425), 
            Vector3.new(480.723, 19.000, 551.553), 
            Vector3.new(478.833, 16.833, 564.528) 
        },
    }, 
    CakeFactory = { 
        loop1 = { 
            Vector3.new(-3622.300, 824.359, 116.033), 
            Vector3.new(-3625.935, 824.359, 143.442), 
            Vector3.new(-3661.278, 824.359, 143.193), 
            Vector3.new(-3659.624, 824.359, 96.457) 
        }, 
        loop2 = { 
            Vector3.new(-3815.605, 824.549, 183.009), 
            Vector3.new(-3796.010, 824.359, 203.336), 
            Vector3.new(-3796.666, 824.358, 258.077), 
            Vector3.new(-3815.980, 824.403, 277.801), 
            Vector3.new(-3826.720, 826.198, 242.588) 
        }, 
        loop3 = { 
            Vector3.new(-3708.517, 824.359, 55.405), 
            Vector3.new(-3688.918, 824.359, 28.038), 
            Vector3.new(-3651.181, 824.359, 23.405), 
            Vector3.new(-3616.981, 824.359, 55.996), 
            Vector3.new(-3658.004, 824.359, 73.701) 
        },
    },
    ["brandon6875935'sPlace"] = { 
        loop1 = { 
            Vector3.new(-3702.259, 72.000, -1935.174), 
            Vector3.new(-3713.998, 72.000, -1959.809), 
            Vector3.new(-3761.527, 72.000, -1969.725), 
            Vector3.new(-3792.447, 72.000, -1945.355), 
            Vector3.new(-3777.453, 72.000, -1891.260), 
            Vector3.new(-3732.691, 72.100, -1893.186), 
            Vector3.new(-3745.861, 89.000, -1949.084) 
        }, 
        loop2 = { 
            Vector3.new(-3564.144, 72.000, -1957.188), 
            Vector3.new(-3564.758, 72.250, -1937.374), 
            Vector3.new(-3590.392, 72.000, -1937.746), 
            Vector3.new(-3582.932, 72.150, -1957.527) 
        }, 
        loop3 = { 
            Vector3.new(-3801.487, 72.000, -2007.373), 
            Vector3.new(-3781.906, 72.000, -2007.177), 
            Vector3.new(-3757.907, 72.000, -1983.777), 
            Vector3.new(-3803.361, 72.000, -1984.333) 
        }, 
    },
    ["Glasshouses[New]"] = { 
        loop1 = { 
            Vector3.new(370.796, 3263.000, -524.878), 
            Vector3.new(356.663, 3262.999, -537.009), 
            Vector3.new(338.020, 3263.000, -536.672), 
            Vector3.new(337.859, 3263.000, -509.536), 
            Vector3.new(370.656, 3263.000, -508.898) 
        }, 
        loop2 = { 
            Vector3.new(472.968, 3263.984, -563.755), 
            Vector3.new(469.227, 3263.000, -582.386), 
            Vector3.new(470.425, 3263.000, -601.091), 
            Vector3.new(488.234, 3263.000, -602.562), 
            Vector3.new(506.456, 3264.164, -596.673), 
            Vector3.new(500.544, 3265.000, -572.950), 
            Vector3.new(487.642, 3265.000, -567.045), 
            Vector3.new(503.610, 3265.000, -585.324) 
        }, 
        loop3 = { 
            Vector3.new(286.507, 3263.000, -643.771), 
            Vector3.new(282.763, 3263.000, -658.657), 
            Vector3.new(285.207, 3263.000, -671.275), 
            Vector3.new(304.226, 3263.000, -669.219), 
            Vector3.new(295.893, 3263.000, -656.623) 
        },
    },
    ["Glasshouses[Normal]"] = { 
        loop1 = {
            Vector3.new(338.275, 3263.000, -536.937), 
            Vector3.new(338.091, 3263.000, -509.203), 
            Vector3.new(370.727, 3263.000, -508.944), 
            Vector3.new(370.906, 3263.000, -524.817), 
            Vector3.new(355.485, 3262.999, -537.204) 
        }, 
        loop2 = { 
            Vector3.new(470.956, 3263.000, -563.440), 
            Vector3.new(469.439, 3263.000, -582.797), 
            Vector3.new(470.736, 3263.000, -601.184), 
            Vector3.new(488.107, 3263.000, -602.717), 
            Vector3.new(506.265, 3264.190, -596.356), 
            Vector3.new(497.543, 3265.000, -579.892), 
            Vector3.new(489.611, 3265.000, -565.767) 
        }, 
        loop3 = { 
            Vector3.new(304.473, 3263.008, -669.296), 
            Vector3.new(298.306, 3263.000, -657.551), 
            Vector3.new(286.298, 3263.000, -643.794), 
            Vector3.new(283.534, 3263.000, -657.084), 
            Vector3.new(284.850, 3263.000, -671.220) 
        },
    },
    HorrorHotel = { 
        loop1 = { 
            Vector3.new(-272.419, 5465.065, -392.473), 
            Vector3.new(-291.346, 5465.065, -414.834), 
            Vector3.new(-284.684, 5464.565, -435.732), 
            Vector3.new(-271.978, 5464.766, -458.878), 
            Vector3.new(-262.390, 5465.065, -445.492), 
            Vector3.new(-255.497, 5465.066, -429.963), 
            Vector3.new(-262.141, 5465.065, -411.214) 
        }, 
        loop2 = { 
            Vector3.new(-293.971, 5465.065, -303.421), 
            Vector3.new(-315.620, 5465.065, -291.078), 
            Vector3.new(-330.204, 5465.065, -296.022), 
            Vector3.new(-331.674, 5464.565, -319.083), 
            Vector3.new(-331.683, 5464.565, -336.884), 
            Vector3.new(-327.392, 5464.665, -352.420), 
            Vector3.new(-315.538, 5465.065, -340.767), 
            Vector3.new(-305.339, 5465.065, -323.829) 
        }, 
        loop3 = { 
            Vector3.new(-244.027, 5470.066, -536.714), 
            Vector3.new(-223.939, 5469.565, -538.617), 
            Vector3.new(-199.916, 5473.566, -539.934), 
            Vector3.new(-197.887, 5472.789, -525.205), 
            Vector3.new(-201.006, 5465.065, -508.555), 
            Vector3.new(-221.831, 5465.065, -512.036), 
            Vector3.new(-245.917, 5465.065, -520.722) 
        },
        barriers = {
            [1] = { 
                Size = Vector3.new(2.00, 10.00, 11.65), 
                Position = Vector3.new(-313.41, 5465.06, -288.02), 
                Rotation = Vector3.new(0.00, 114.26, 0.00) 
            },
            [2] = { 
                Size = Vector3.new(2.00, 10.00, 12.29), 
                Position = Vector3.new(-313.76, 5465.07, -297.13), 
                Rotation = Vector3.new(0.00, 107.10, 0.00) 
            },
            [3] = { 
                Size = Vector3.new(2.00, 10.00, 2.80), 
                Position = Vector3.new(-309.30, 5465.06, -300.11), 
                Rotation = Vector3.new(-0.03, -12.34, 0.00) 
            },
            [4] = { 
                Size = Vector3.new(2.00, 10.00, 14.86), 
                Position = Vector3.new(-320.16, 5465.12, -279.15), 
                Rotation = Vector3.new(-0.39, 173.35, 0.00) 
            },
            [5] = { 
                Size = Vector3.new(2.00, 10.00, 12.14), 
                Position = Vector3.new(-315.11, 5465.06, -270.39), 
                Rotation = Vector3.new(0.00, -103.21, 0.00) 
            },
            [6] = { 
                Size = Vector3.new(2.00, 10.00, 20.32), 
                Position = Vector3.new(-309.01, 5465.07, -279.80), 
                Rotation = Vector3.new(0.00, 176.47, 0.00) 
            },
            [7] = { 
                Size = Vector3.new(2.00, 10.00, 22.96), 
                Position = Vector3.new(-314.50, 5465.07, -259.91), 
                Rotation = Vector3.new(0.00, -105.16, 0.00) 
            },
            [8] = { 
                Size = Vector3.new(2.00, 5.00, 6.28), 
                Position = Vector3.new(-249.54, 5465.07, -533.97), 
                Rotation = Vector3.new(0.00, 90.52, 0.00) 
            },
        },
    },
    BeachHouseParadise = {
        loop1 = {
            Vector3.new(-703.553, 22.819, 2260.722), 
            Vector3.new(-723.728, 23.069, 2263.855), 
            Vector3.new(-740.410, 22.819, 2263.990), 
            Vector3.new(-739.666, 22.819, 2250.721), 
            Vector3.new(-721.699, 22.819, 2254.402) 
        }, 
        loop2 = { 
            Vector3.new(-699.401, 22.504, 2220.934), 
            Vector3.new(-713.211, 23.545, 2211.273), 
            Vector3.new(-712.343, 24.719, 2184.330), 
            Vector3.new(-702.179, 24.569, 2182.874), 
            Vector3.new(-693.827, 24.500, 2197.261) 
        }, 
        loop3 = { 
            Vector3.new(-502.842, 22.019, 2158.992), 
            Vector3.new(-508.039, 22.818, 2175.378), 
            Vector3.new(-483.741, 23.069, 2181.293), 
            Vector3.new(-480.167, 23.069, 2161.001) 
        },
        barriers = {
            [1] = { 
                Size = Vector3.new(2.00, 10.00, 16.81), 
                Position = Vector3.new(-656.34, 28.19, 2198.00), 
                Rotation = Vector3.new(0.40, 34.44, 0.00) 
            },
            [2] = { 
                Size = Vector3.new(2.00, 10.00, 26.30), 
                Position = Vector3.new(-668.47, 28.25, 2162.50), 
                Rotation = Vector3.new(0.00, 0.68, 0.00) 
            },
            [3] = { 
                Size = Vector3.new(2.00, 10.00, 25.46), 
                Position = Vector3.new(-634.57, 28.25, 2119.40), 
                Rotation = Vector3.new(0.00, -90.07, 0.00) 
            },
            [4] = { 
                Size = Vector3.new(2.00, 10.00, 17.53), 
                Position = Vector3.new(-613.81, 28.25, 2126.30), 
                Rotation = Vector3.new(0.00, -142.18, 0.00) 
            },
            [5] = { 
                Size = Vector3.new(2.00, 10.00, 28.28), 
                Position = Vector3.new(-601.38, 28.25, 2161.82), 
                Rotation = Vector3.new(0.00, -178.74, 0.00) 
            },
            [6] = { 
                Size = Vector3.new(2.00, 10.00, 20.49), 
                Position = Vector3.new(-614.24, 28.25, 2197.29), 
                Rotation = Vector3.new(0.00, 138.26, 0.00) 
            },
        },
    },
    NaturalDisasterSurvival = { 
        loop1 = { 
            Vector3.new(9953.938, 327.566, -2648.129), 
            Vector3.new(9948.070, 327.281, -2673.033), 
            Vector3.new(9947.548, 327.281, -2697.402), 
            Vector3.new(9964.258, 327.281, -2697.534), 
            Vector3.new(9961.733, 327.281, -2673.142) 
        }, 
        loop2 = { 
            Vector3.new(10072.606, 337.897, -2539.132), 
            Vector3.new(10053.114, 337.897, -2541.664), 
            Vector3.new(10034.344, 337.897, -2540.978), 
            Vector3.new(10035.175, 337.897, -2525.177), 
            Vector3.new(10034.228, 337.897, -2512.038), 
            Vector3.new(10054.807, 338.305, -2519.479) 
        }, 
        loop3 = { 
            Vector3.new(10018.221, 337.896, -2490.300), 
            Vector3.new(10016.170, 332.579, -2510.994), 
            Vector3.new(10012.885, 326.396, -2542.261), 
            Vector3.new(10015.260, 326.449, -2567.336), 
            Vector3.new(10043.567, 326.281, -2573.663), 
            Vector3.new(10066.047, 326.281, -2581.713), 
            Vector3.new(10093.337, 326.281, -2590.591), 
            Vector3.new(10098.621, 331.483, -2575.438), 
            Vector3.new(10095.696, 338.303, -2557.172), 
            Vector3.new(10073.460, 337.897, -2550.145), 
            Vector3.new(10053.191, 337.897, -2546.174), 
            Vector3.new(10034.080, 337.897, -2539.792), 
            Vector3.new(10026.372, 337.897, -2513.997) 
        },
    },
    ["Yorick'sRestingPlace[Halloween]"] = { 
        loop1 = { 
            Vector3.new(-295.892, 399.446, -1347.912), 
            Vector3.new(-305.335, 391.082, -1346.886), 
            Vector3.new(-325.042, 391.082, -1326.026), 
            Vector3.new(-323.070, 391.082, -1299.581), 
            Vector3.new(-301.136, 391.082, -1319.141) 
        }, 
        loop2 = { 
            Vector3.new(-561.260, 408.472, -1025.577), 
            Vector3.new(-540.649, 408.472, -1007.847), 
            Vector3.new(-514.633, 408.472, -1026.019), 
            Vector3.new(-540.286, 409.012, -1032.197) 
        }, 
        loop3 = { 
            Vector3.new(-441.457, 391.047, -1296.507), 
            Vector3.new(-443.234, 391.047, -1318.291), 
            Vector3.new(-441.317, 391.047, -1340.996), 
            Vector3.new(-439.684, 391.047, -1317.937) 
        }, 
        barriers = {
            [1] = { 
                Size = Vector3.new(2.00, 10.00, 35.76), 
                Position = Vector3.new(-513.08, 393.07, -1276.75), 
                Rotation = Vector3.new(0.00, 5.96, 0.00) 
            },
            [2] = { 
                Size = Vector3.new(2.00, 10.00, 68.01), 
                Position = Vector3.new(-550.55, 393.07, -1297.62), 
                Rotation = Vector3.new(0.00, 86.76, 0.00) 
            },
            [3] = { 
                Size = Vector3.new(2.00, 10.00, 39.60), 
                Position = Vector3.new(-605.13, 394.07, -1302.95), 
                Rotation = Vector3.new(0.00, 81.23, 0.00) 
            },
            [4] = { 
                Size = Vector3.new(2.00, 10.00, 18.92), 
                Position = Vector3.new(-533.29, 393.07, -1268.38), 
                Rotation = Vector3.new(0.00, 7.47, 0.00) 
            },
            [5] = { 
                Size = Vector3.new(2.00, 10.00, 91.23), 
                Position = Vector3.new(-580.11, 393.57, -1279.10), 
                Rotation = Vector3.new(0.63, 88.32, 0.00) 
            },
            [6] = { 
                Size = Vector3.new(2.00, 10.00, 61.51), 
                Position = Vector3.new(-508.71, 393.07, -1214.80), 
                Rotation = Vector3.new(0.00, -176.44, 0.00) 
            },
            [7] = { 
                Size = Vector3.new(2.00, 10.00, 15.81), 
                Position = Vector3.new(-499.04, 393.07, -1183.52), 
                Rotation = Vector3.new(0.00, -93.94, 0.00) 
            },
            [8] = { 
                Size = Vector3.new(2.00, 10.00, 37.92), 
                Position = Vector3.new(-458.80, 393.07, -1184.48), 
                Rotation = Vector3.new(0.00, -85.03, 0.00) 
            },
            [9] = { 
                Size = Vector3.new(2.00, 10.00, 25.58), 
                Position = Vector3.new(-438.24, 393.07, -1199.57), 
                Rotation = Vector3.new(0.00, -2.78, 0.00) 
            },
            [10] = { 
                Size = Vector3.new(2.00, 10.00, 18.69), 
                Position = Vector3.new(-438.57, 393.07, -1241.36), 
                Rotation = Vector3.new(0.00, -8.81, 0.00) 
            },
            [11] = { 
                Size = Vector3.new(2.00, 10.00, 125.09), 
                Position = Vector3.new(-374.69, 393.07, -1247.13), 
                Rotation = Vector3.new(0.00, -93.17, 0.00) 
            },
            [12] = { 
                Size = Vector3.new(2.00, 10.00, 46.42), 
                Position = Vector3.new(-308.18, 393.07, -1220.82), 
                Rotation = Vector3.new(0.00, -169.92, 0.00) 
            },
            [13] = { 
                Size = Vector3.new(2.00, 10.00, 90.98), 
                Position = Vector3.new(-293.84, 393.59, -1139.56), 
                Rotation = Vector3.new(0.61, -171.17, 0.00) 
            },
            [14] = { 
                Size = Vector3.new(2.00, 10.00, 90.58), 
                Position = Vector3.new(-322.25, 393.57, -1139.22), 
                Rotation = Vector3.new(0.63, -177.83, 0.00) 
            },
            [15] = { 
                Size = Vector3.new(2.00, 10.00, 28.92), 
                Position = Vector3.new(-326.56, 393.32, -1212.28), 
                Rotation = Vector3.new(0.98, 8.66, 0.00) 
            },
            [16] = { 
                Size = Vector3.new(2.00, 10.00, 92.15), 
                Position = Vector3.new(-377.00, 393.07, -1229.28), 
                Rotation = Vector3.new(0.00, 85.31, 0.00) 
            },
            [17] = { 
                Size = Vector3.new(2.00, 10.00, 43.27), 
                Position = Vector3.new(-422.58, 393.57, -1190.82), 
                Rotation = Vector3.new(1.32, 174.28, 0.00) 
            },
            [18] = { 
                Size = Vector3.new(2.00, 10.00, 52.72), 
                Position = Vector3.new(-451.47, 393.57, -1167.22), 
                Rotation = Vector3.new(-1.09, 95.19, 0.00) 
            },
            [19] = { 
                Size = Vector3.new(2.00, 10.00, 17.56), 
                Position = Vector3.new(-430.92, 393.07, -1232.56), 
                Rotation = Vector3.new(0.00, -85.95, 0.00) 
            },
            [20] = { 
                Size = Vector3.new(2.00, 10.00, 18.20), 
                Position = Vector3.new(-429.75, 392.67, -1212.22), 
                Rotation = Vector3.new(-2.55, 87.68, 0.00) 
            },
            [21] = { 
                Size = Vector3.new(2.00, 10.00, 13.34), 
                Position = Vector3.new(-498.05, 393.07, -1165.68), 
                Rotation = Vector3.new(0.00, 89.82, 0.00) 
            },
            [22] = { 
                Size = Vector3.new(2.00, 10.00, 15.81), 
                Position = Vector3.new(-505.24, 393.07, -1157.81), 
                Rotation = Vector3.new(0.00, 176.20, 0.00) 
            },
            [23] = { 
                Size = Vector3.new(2.00, 10.00, 33.47), 
                Position = Vector3.new(-522.56, 393.07, -1149.46), 
                Rotation = Vector3.new(0.00, -85.93, 0.00) 
            },
            [24] = { 
                Size = Vector3.new(2.00, 10.00, 35.00), 
                Position = Vector3.new(-539.34, 393.07, -1130.45), 
                Rotation = Vector3.new(0.00, 177.39, 0.00) 
            },
            [25] = { 
                Size = Vector3.new(2.00, 10.00, 53.03), 
                Position = Vector3.new(-557.55, 393.07, -1139.34), 
                Rotation = Vector3.new(0.00, -5.88, 0.00) 
            },
            [26] = { 
                Size = Vector3.new(2.00, 10.00, 13.82), 
                Position = Vector3.new(-547.92, 393.07, -1165.73), 
                Rotation = Vector3.new(0.00, -89.93, 0.00) 
            },
            [27] = { 
                Size = Vector3.new(2.00, 10.00, 80.27), 
                Position = Vector3.new(-536.57, 393.07, -1205.63), 
                Rotation = Vector3.new(0.00, -6.35, 0.00) 
            },
        },
    },
    ["Yorick'sRestingPlace[Normal]"] = { 
        loop1 = { 
            Vector3.new(-295.892, 399.446, -1347.912), 
            Vector3.new(-305.335, 391.082, -1346.886), 
            Vector3.new(-325.042, 391.082, -1326.026), 
            Vector3.new(-323.070, 391.082, -1299.581), 
            Vector3.new(-301.136, 391.082, -1319.141) 
        }, 
        loop2 = { 
            Vector3.new(-561.260, 408.472, -1025.577), 
            Vector3.new(-540.649, 408.472, -1007.847), 
            Vector3.new(-514.633, 408.472, -1026.019), 
            Vector3.new(-540.286, 409.012, -1032.197) 
        }, 
        loop3 = { 
            Vector3.new(-441.457, 391.047, -1296.507), 
            Vector3.new(-443.234, 391.047, -1318.291), 
            Vector3.new(-441.317, 391.047, -1340.996), 
            Vector3.new(-439.684, 391.047, -1317.937) 
        }, 
        barriers = {
            [1] = { 
                Size = Vector3.new(2.00, 10.00, 35.76), 
                Position = Vector3.new(-513.08, 393.07, -1276.75), 
                Rotation = Vector3.new(0.00, 5.96, 0.00) 
            },
            [2] = { 
                Size = Vector3.new(2.00, 10.00, 68.01), 
                Position = Vector3.new(-550.55, 393.07, -1297.62), 
                Rotation = Vector3.new(0.00, 86.76, 0.00) 
            },
            [3] = { 
                Size = Vector3.new(2.00, 10.00, 39.60), 
                Position = Vector3.new(-605.13, 394.07, -1302.95), 
                Rotation = Vector3.new(0.00, 81.23, 0.00) 
            },
            [4] = { 
                Size = Vector3.new(2.00, 10.00, 18.92), 
                Position = Vector3.new(-533.29, 393.07, -1268.38), 
                Rotation = Vector3.new(0.00, 7.47, 0.00) 
            },
            [5] = { 
                Size = Vector3.new(2.00, 10.00, 91.23), 
                Position = Vector3.new(-580.11, 393.57, -1279.10), 
                Rotation = Vector3.new(0.63, 88.32, 0.00) 
            },
            [6] = { 
                Size = Vector3.new(2.00, 10.00, 61.51), 
                Position = Vector3.new(-508.71, 393.07, -1214.80), 
                Rotation = Vector3.new(0.00, -176.44, 0.00) 
            },
            [7] = { 
                Size = Vector3.new(2.00, 10.00, 15.81), 
                Position = Vector3.new(-499.04, 393.07, -1183.52), 
                Rotation = Vector3.new(0.00, -93.94, 0.00) 
            },
            [8] = { 
                Size = Vector3.new(2.00, 10.00, 37.92), 
                Position = Vector3.new(-458.80, 393.07, -1184.48), 
                Rotation = Vector3.new(0.00, -85.03, 0.00) 
            },
            [9] = { 
                Size = Vector3.new(2.00, 10.00, 25.58), 
                Position = Vector3.new(-438.24, 393.07, -1199.57), 
                Rotation = Vector3.new(0.00, -2.78, 0.00) 
            },
            [10] = { 
                Size = Vector3.new(2.00, 10.00, 18.69), 
                Position = Vector3.new(-438.57, 393.07, -1241.36), 
                Rotation = Vector3.new(0.00, -8.81, 0.00) 
            },
            [11] = { 
                Size = Vector3.new(2.00, 10.00, 125.09), 
                Position = Vector3.new(-374.69, 393.07, -1247.13), 
                Rotation = Vector3.new(0.00, -93.17, 0.00) 
            },
            [12] = { 
                Size = Vector3.new(2.00, 10.00, 46.42), 
                Position = Vector3.new(-308.18, 393.07, -1220.82), 
                Rotation = Vector3.new(0.00, -169.92, 0.00) 
            },
            [13] = { 
                Size = Vector3.new(2.00, 10.00, 90.98), 
                Position = Vector3.new(-293.84, 393.59, -1139.56), 
                Rotation = Vector3.new(0.61, -171.17, 0.00) 
            },
            [14] = { 
                Size = Vector3.new(2.00, 10.00, 90.58), 
                Position = Vector3.new(-322.25, 393.57, -1139.22), 
                Rotation = Vector3.new(0.63, -177.83, 0.00) 
            },
            [15] = { 
                Size = Vector3.new(2.00, 10.00, 28.92), 
                Position = Vector3.new(-326.56, 393.32, -1212.28), 
                Rotation = Vector3.new(0.98, 8.66, 0.00) 
            },
            [16] = { 
                Size = Vector3.new(2.00, 10.00, 92.15), 
                Position = Vector3.new(-377.00, 393.07, -1229.28), 
                Rotation = Vector3.new(0.00, 85.31, 0.00) 
            },
            [17] = { 
                Size = Vector3.new(2.00, 10.00, 43.27), 
                Position = Vector3.new(-422.58, 393.57, -1190.82), 
                Rotation = Vector3.new(1.32, 174.28, 0.00) 
            },
            [18] = { 
                Size = Vector3.new(2.00, 10.00, 52.72), 
                Position = Vector3.new(-451.47, 393.57, -1167.22), 
                Rotation = Vector3.new(-1.09, 95.19, 0.00) 
            },
            [19] = { 
                Size = Vector3.new(2.00, 10.00, 17.56), 
                Position = Vector3.new(-430.92, 393.07, -1232.56), 
                Rotation = Vector3.new(0.00, -85.95, 0.00) 
            },
            [20] = { 
                Size = Vector3.new(2.00, 10.00, 18.20), 
                Position = Vector3.new(-429.75, 392.67, -1212.22), 
                Rotation = Vector3.new(-2.55, 87.68, 0.00) 
            },
            [21] = { 
                Size = Vector3.new(2.00, 10.00, 13.34), 
                Position = Vector3.new(-498.05, 393.07, -1165.68), 
                Rotation = Vector3.new(0.00, 89.82, 0.00) 
            },
            [22] = { 
                Size = Vector3.new(2.00, 10.00, 15.81), 
                Position = Vector3.new(-505.24, 393.07, -1157.81), 
                Rotation = Vector3.new(0.00, 176.20, 0.00) 
            },
            [23] = { 
                Size = Vector3.new(2.00, 10.00, 33.47), 
                Position = Vector3.new(-522.56, 393.07, -1149.46), 
                Rotation = Vector3.new(0.00, -85.93, 0.00) 
            },
            [24] = { 
                Size = Vector3.new(2.00, 10.00, 35.00), 
                Position = Vector3.new(-539.34, 393.07, -1130.45), 
                Rotation = Vector3.new(0.00, 177.39, 0.00) 
            },
            [25] = { 
                Size = Vector3.new(2.00, 10.00, 53.03), 
                Position = Vector3.new(-557.55, 393.07, -1139.34), 
                Rotation = Vector3.new(0.00, -5.88, 0.00) 
            },
            [26] = { 
                Size = Vector3.new(2.00, 10.00, 13.82), 
                Position = Vector3.new(-547.92, 393.07, -1165.73), 
                Rotation = Vector3.new(0.00, -89.93, 0.00) 
            },
            [27] = { 
                Size = Vector3.new(2.00, 10.00, 80.27), 
                Position = Vector3.new(-536.57, 393.07, -1205.63), 
                Rotation = Vector3.new(0.00, -6.35, 0.00) 
            },
        },
    },
    ["UltimateAssassinGrounds[Normal]"] = { 
        loop1 = { 
            Vector3.new(-76.037, 47.000, 233.334), 
            Vector3.new(-74.467, 39.000, 272.176), 
            Vector3.new(-96.939, 39.000, 283.860), 
            Vector3.new(-101.722, 47.000, 259.132) 
        }, 
        loop2 = { 
            Vector3.new(-192.185, 39.000, 483.795), 
            Vector3.new(-171.058, 39.000, 479.348), 
            Vector3.new(-179.246, 40.000, 437.305), 
            Vector3.new(-193.334, 38.000, 436.986) 
        },
        loop3 = { 
            Vector3.new(-113.197, 46.368, 508.340), 
            Vector3.new(-109.609, 51.000, 554.393), 
            Vector3.new(-141.512, 50.997, 561.259), 
            Vector3.new(-142.151, 41.000, 501.514) 
        }, 
        barriers = {
            [1] = { 
                Size = Vector3.new(2.00, 10.00, 30.88), 
                Position = Vector3.new(-133.87, 40.45, 447.80), 
                Rotation = Vector3.new(-2.04, 28.87, 0.00) 
            },
            [2] = { 
                Size = Vector3.new(2.00, 10.00, 43.99), 
                Position = Vector3.new(-118.83, 39.12, 434.49), 
                Rotation = Vector3.new(1.25, -89.77, 0.00) 
            },
            [3] = { 
                Size = Vector3.new(2.00, 10.00, 27.34), 
                Position = Vector3.new(-92.30, 41.54, 448.03), 
                Rotation = Vector3.new(6.12, -167.38, 0.00) 
            },
            [4] = { 
                Size = Vector3.new(2.00, 10.00, 19.06), 
                Position = Vector3.new(-56.97, 39.75, 407.24), 
                Rotation = Vector3.new(6.20, -178.40, 0.00) 
            },
            [5] = { 
                Size = Vector3.new(2.00, 10.00, 20.39), 
                Position = Vector3.new(-56.02, 39.08, 371.96), 
                Rotation = Vector3.new(-4.13, -2.19, 0.00) 
            },
            [6] = { 
                Size = Vector3.new(2.00, 10.00, 14.11), 
                Position = Vector3.new(-55.21, 39.39, 342.20), 
                Rotation = Vector3.new(0.98, -2.50, 0.00) 
            },
        },
    },
    ["UltimateAssassinGrounds[Sakura]"] = { 
        loop1 = { 
            Vector3.new(-76.037, 47.000, 233.334), 
            Vector3.new(-74.467, 39.000, 272.176), 
            Vector3.new(-96.939, 39.000, 283.860), 
            Vector3.new(-101.722, 47.000, 259.132) 
        }, 
        loop2 = { 
            Vector3.new(-192.185, 39.000, 483.795), 
            Vector3.new(-171.058, 39.000, 479.348), 
            Vector3.new(-179.246, 40.000, 437.305), 
            Vector3.new(-193.334, 38.000, 436.986) 
        },
        loop3 = { 
            Vector3.new(-113.197, 46.368, 508.340), 
            Vector3.new(-109.609, 51.000, 554.393), 
            Vector3.new(-141.512, 50.997, 561.259), 
            Vector3.new(-142.151, 41.000, 501.514) 
        }, 
        barriers = {
            [1] = { 
                Size = Vector3.new(2.00, 10.00, 30.88), 
                Position = Vector3.new(-133.87, 40.45, 447.80), 
                Rotation = Vector3.new(-2.04, 28.87, 0.00) 
            },
            [2] = { 
                Size = Vector3.new(2.00, 10.00, 43.99), 
                Position = Vector3.new(-118.83, 39.12, 434.49), 
                Rotation = Vector3.new(1.25, -89.77, 0.00) 
            },
            [3] = { 
                Size = Vector3.new(2.00, 10.00, 27.34), 
                Position = Vector3.new(-92.30, 41.54, 448.03), 
                Rotation = Vector3.new(6.12, -167.38, 0.00) 
            },
            [4] = { 
                Size = Vector3.new(2.00, 10.00, 19.06), 
                Position = Vector3.new(-56.97, 39.75, 407.24), 
                Rotation = Vector3.new(6.20, -178.40, 0.00) 
            },
            [5] = { 
                Size = Vector3.new(2.00, 10.00, 20.39), 
                Position = Vector3.new(-56.02, 39.08, 371.96), 
                Rotation = Vector3.new(-4.13, -2.19, 0.00) 
            },
            [6] = { 
                Size = Vector3.new(2.00, 10.00, 14.11), 
                Position = Vector3.new(-55.21, 39.39, 342.20), 
                Rotation = Vector3.new(0.98, -2.50, 0.00) 
            },
        },
    },
    ["FamiliarRuins[Normal]"] = { 
        loop1 = { 
            Vector3.new(-590.069, 350.473, -992.130), 
            Vector3.new(-618.200, 350.473, -990.508), 
            Vector3.new(-643.700, 350.474, -993.299), 
            Vector3.new(-619.392, 350.473, -1000.797) 
        }, 
        loop2 = { 
            Vector3.new(-657.414, 350.473, -893.994), 
            Vector3.new(-692.389, 350.473, -893.205), 
            Vector3.new(-675.199, 350.473, -892.981), 
            Vector3.new(-690.676, 351.684, -878.109), 
            Vector3.new(-660.104, 350.473, -868.527) 
        }, 
        loop3 = { 
            Vector3.new(-902.044, 360.373, -921.421), 
            Vector3.new(-910.440, 360.371, -932.909), 
            Vector3.new(-908.807, 360.371, -949.047), 
            Vector3.new(-901.328, 360.371, -935.215) 
        }, 
    },
    ["C00lCarnival[Normal]"] = { 
        loop1 = { 
            Vector3.new(2168.750, 398.100, -534.732), 
            Vector3.new(2187.287, 397.600, -542.203), 
            Vector3.new(2200.867, 397.600, -532.074), 
            Vector3.new(2201.219, 398.100, -512.059), 
            Vector3.new(2174.893, 398.200, -512.526) 
        }, 
        loop2 = { 
            Vector3.new(2264.167, 397.600, -451.858), 
            Vector3.new(2264.311, 397.600, -423.763), 
            Vector3.new(2297.124, 397.600, -424.258), 
            Vector3.new(2296.829, 398.100, -452.198) 
        }, 
        loop3 = { 
            Vector3.new(2316.921, 405.900, -631.197), 
            Vector3.new(2312.305, 405.600, -609.797), 
            Vector3.new(2325.179, 399.600, -589.640), 
            Vector3.new(2362.215, 399.600, -601.585) 
        }, 
    },
    TheTempest = { 
        loop1 = { 
            Vector3.new(-175.813, 378.183, -276.585), 
            Vector3.new(-184.809, 383.933, -262.584), 
            Vector3.new(-211.252, 384.578, -275.662), 
            Vector3.new(-200.291, 383.933, -289.428) 
        }, 
        loop2 = { 
            Vector3.new(-132.071, 383.933, -333.195), 
            Vector3.new(-163.120, 383.933, -316.968), 
            Vector3.new(-145.021, 380.896, -312.529), 
            Vector3.new(-128.939, 381.933, -313.346) 
        }, 
        loop3 = { 
            Vector3.new(-145.289, 385.083, -200.410), 
            Vector3.new(-134.327, 377.183, -215.144), 
            Vector3.new(-73.542, 377.933, -214.449), 
            Vector3.new(-50.482, 377.183, -203.722), 
            Vector3.new(-52.355, 384.809, -164.664), 
            Vector3.new(-106.265, 384.933, -177.584) 
        }, 
        barriers = {
            [1] = { 
                Size = Vector3.new(2.00, 10.00, 68.64), 
                Position = Vector3.new(1.71, 381.35, -393.40), 
                Rotation = Vector3.new(0.70, -177.62, 0.00) 
            },
            [2] = { 
                Size = Vector3.new(2.00, 10.00, 15.49), 
                Position = Vector3.new(16.59, 380.94, -366.70), 
                Rotation = Vector3.new(0.17, -32.41, 0.00) 
            },
            [3] = { 
                Size = Vector3.new(2.00, 10.00, 41.50), 
                Position = Vector3.new(12.36, 380.96, -323.93), 
                Rotation = Vector3.new(1.61, -0.62, 0.00) 
            },
            [4] = { 
                Size = Vector3.new(2.00, 10.00, 19.84), 
                Position = Vector3.new(14.24, 381.89, -279.13), 
                Rotation = Vector3.new(-6.02, 176.21, 0.00) 
            },
            [5] = { 
                Size = Vector3.new(2.00, 10.00, 22.19), 
                Position = Vector3.new(24.17, 380.39, -266.00), 
                Rotation = Vector3.new(-2.38, -107.26, 0.00) 
            },
            [6] = { 
                Size = Vector3.new(2.00, 10.00, 10.60), 
                Position = Vector3.new(54.48, 379.93, -263.05), 
                Rotation = Vector3.new(0.00, -94.22, 0.00) 
            },
            [7] = { 
                Size = Vector3.new(2.00, 10.00, 10.76), 
                Position = Vector3.new(54.37, 379.46, -253.24), 
                Rotation = Vector3.new(3.61, 89.60, 0.00) 
            },
            [8] = { 
                Size = Vector3.new(2.00, 10.00, 32.46), 
                Position = Vector3.new(18.48, 379.86, -254.34), 
                Rotation = Vector3.new(0.12, 87.06, 0.00) 
            },
            [9] = { 
                Size = Vector3.new(2.00, 10.00, 32.22), 
                Position = Vector3.new(2.40, 380.18, -272.66), 
                Rotation = Vector3.new(0.89, -6.27, 0.00) 
            },
            [10] = { 
                Size = Vector3.new(2.00, 10.00, 41.45), 
                Position = Vector3.new(3.44, 381.44, -323.84), 
                Rotation = Vector3.new(-0.56, -0.62, 0.00) 
            },
        },
    },

    PirateBay = { 
        loop1 = { 
            Vector3.new(-419.504, 568.225, -116.262), 
            Vector3.new(-444.370, 563.200, -101.424), 
            Vector3.new(-414.857, 563.220, -93.729), 
            Vector3.new(-388.285, 563.200, -100.118), 
            Vector3.new(-390.291, 568.200, -117.607) 
        }, 
        loop2 = { 
            Vector3.new(-337.559, 570.200, 25.907), 
            Vector3.new(-348.376, 570.200, 46.254), 
            Vector3.new(-340.666, 570.200, 79.712), 
            Vector3.new(-337.892, 575.700, 53.903) 
        }, 
        loop3 = { 
            Vector3.new(-374.424, 570.200, 97.555), 
            Vector3.new(-320.669, 570.200, 99.879), 
            Vector3.new(-322.598, 570.200, 115.862), 
            Vector3.new(-337.559, 570.200, 126.381), 
            Vector3.new(-362.096, 570.200, 115.483) 
        }, 
        barriers = {
            [1] = { 
                Size = Vector3.new(2.00, 10.00, 19.67), 
                Position = Vector3.new(-340.81, 564.12, -6.91), 
                Rotation = Vector3.new(0.44, 178.73, 0.00) 
            },
            [2] = { 
                Size = Vector3.new(2.00, 10.00, 21.78), 
                Position = Vector3.new(-352.10, 564.20, -14.46), 
                Rotation = Vector3.new(0.00, 93.54, 0.00) 
            },
            [3] = { 
                Size = Vector3.new(2.00, 10.00, 19.37), 
                Position = Vector3.new(-296.61, 564.20, -14.32), 
                Rotation = Vector3.new(0.00, -91.70, 0.00) 
            },
            [4] = { 
                Size = Vector3.new(2.00, 10.00, 19.02), 
                Position = Vector3.new(-305.47, 564.42, -5.56), 
                Rotation = Vector3.new(1.30, -178.02, 0.00) 
            },
        },
    },
    WorkataPizzaPlace = { 
        loop1 = { 
            Vector3.new(1637.163, 1136.707, 270.242), 
            Vector3.new(1667.723, 1136.707, 267.797), 
            Vector3.new(1667.286, 1147.182, 251.120), 
            Vector3.new(1667.336, 1136.707, 235.104), 
            Vector3.new(1634.921, 1136.707, 233.923) 
        }, 
        loop2 = { 
            Vector3.new(1404.717, 1136.782, 204.934), 
            Vector3.new(1401.573, 1136.532, 171.134), 
            Vector3.new(1436.098, 1136.532, 173.541) 
        }, 
        loop3 = { 
            Vector3.new(1527.904, 1136.782, 348.468), 
            Vector3.new(1509.037, 1136.782, 342.087), 
            Vector3.new(1507.318, 1136.532, 317.470), 
            Vector3.new(1531.276, 1136.532, 317.283) 
        }, 
    },
    ["PlanetVoss[Aurora]"] = { 
        loop1 = { 
            Vector3.new(1061.766, 3078.000, 57.984), 
            Vector3.new(1030.452, 3080.000, 95.204), 
            Vector3.new(1027.682, 3079.000, 55.025) 
        }, 
        loop2 = { 
            Vector3.new(1223.267, 3078.999, -68.104), 
            Vector3.new(1236.734, 3078.000, -63.192), 
            Vector3.new(1236.734, 3078.000, -18.993), 
            Vector3.new(1222.111, 3079.000, -19.325), 
            Vector3.new(1224.518, 3079.000, -42.764) 
        }, 
        loop3 = {}
    },
    ["PlanetVoss[Normal]"] = { 
        loop1 = { 
            Vector3.new(1030.261, 3080.000, 95.181), 
            Vector3.new(1028.442, 3079.000, 54.751), 
            Vector3.new(1061.716, 3078.000, 57.943) 
        }, 
        loop2 = { 
            Vector3.new(1222.408, 3078.000, -18.533), 
            Vector3.new(1236.578, 3078.000, -18.207), 
            Vector3.new(1236.674, 3078.000, -66.503), 
            Vector3.new(1223.353, 3079.000, -69.995), 
            Vector3.new(1229.227, 3079.981, -42.931) 
        }, 
        loop3 = {}
    },
    ["FamiliarRuins[Classic]"] = { 
        loop1 = { 
            Vector3.new(176.933, 338.673, -34.531), 
            Vector3.new(147.401, 338.673, -42.887), 
            Vector3.new(123.335, 338.673, -34.032), 
            Vector3.new(148.355, 338.673, -32.481) 
        }, 
        loop2 = { 
            Vector3.new(107.275, 338.673, 89.405), 
            Vector3.new(110.083, 338.667, 64.917), 
            Vector3.new(74.520, 338.673, 64.830), 
            Vector3.new(74.346, 339.979, 79.102) 
        }, 
        loop3 = { 
            Vector3.new(-135.082, 348.556, 36.615), 
            Vector3.new(-143.345, 348.571, 24.679), 
            Vector3.new(-144.209, 348.571, 9.853), 
            Vector3.new(-135.959, 349.571, 20.697) 
        }, 
    },
    ["UndergroundWar[Normal]"] = { 
        loop1 = { 
            Vector3.new(-1592.722, 4431.752, -45.823), 
            Vector3.new(-1620.933, 4412.000, -23.123), 
            Vector3.new(-1665.941, 4412.000, 25.748), 
            Vector3.new(-1656.148, 4412.000, 72.496), 
            Vector3.new(-1641.730, 4412.027, 94.573), 
            Vector3.new(-1608.030, 4433.411, 93.687), 
            Vector3.new(-1590.639, 4434.000, 74.585), 
            Vector3.new(-1619.846, 4434.000, 27.758), 
            Vector3.new(-1627.717, 4434.000, -25.949), 
            Vector3.new(-1610.522, 4433.999, -66.066), 
            Vector3.new(-1591.903, 4434.000, -64.893) 
        }, 
        loop2 = { 
            Vector3.new(-1720.326, 4433.854, 1.658), 
            Vector3.new(-1720.160, 4412.000, -39.636), 
            Vector3.new(-1688.660, 4412.000, -70.087), 
            Vector3.new(-1685.810, 4412.000, -89.924), 
            Vector3.new(-1702.076, 4412.000, -125.144), 
            Vector3.new(-1703.431, 4412.000, -144.240), 
            Vector3.new(-1733.769, 4433.928, -144.066), 
            Vector3.new(-1737.748, 4434.000, -123.993), 
            Vector3.new(-1727.046, 4434.000, -78.046), 
            Vector3.new(-1717.177, 4433.999, -25.726) 
        }, 
        loop3 = { 
            Vector3.new(-1656.485, 4434.000, -26.275), 
            Vector3.new(-1683.425, 4433.999, -9.718), 
            Vector3.new(-1686.617, 4434.000, -27.160) 
        }, 
    },
    ["UndergroundWar[Memories]"] = { 
        loop1 = { 
            Vector3.new(-203.580, 4412.000, -143.810), 
            Vector3.new(-234.905, 4433.999, -143.876), 
            Vector3.new(-234.939, 4433.999, -121.472), 
            Vector3.new(-225.342, 4433.999, -78.536), 
            Vector3.new(-216.207, 4434.000, -25.719), 
            Vector3.new(-219.311, 4433.619, 0.298), 
            Vector3.new(-218.673, 4412.000, -44.434), 
            Vector3.new(-185.520, 4412.000, -73.376), 
            Vector3.new(-182.732, 4412.000, -146.254) 
        }, 
        loop2 = { 
            Vector3.new(-92.179, 4434.000, -48.646), 
            Vector3.new(-122.249, 4412.000, -18.669), 
            Vector3.new(-164.910, 4412.000, 23.115), 
            Vector3.new(-155.660, 4412.000, 73.143), 
            Vector3.new(-140.890, 4412.314, 93.236), 
            Vector3.new(-107.959, 4433.595, 93.649), 
            Vector3.new(-91.867, 4434.000, 74.184), 
            Vector3.new(-116.383, 4434.000, 45.382), 
            Vector3.new(-128.758, 4434.000, -26.157), 
            Vector3.new(-127.863, 4433.999, -52.963), 
            Vector3.new(-111.223, 4434.000, -65.836), 
            Vector3.new(-92.766, 4434.000, -65.975) 
        }, 
        loop3 = { 
            Vector3.new(-157.163, 4434.000, -25.792), 
            Vector3.new(-183.313, 4433.999, -6.973), 
            Vector3.new(-187.540, 4434.020, -28.697) 
        }, 
    },
    ["C00lCarnival[Bluu]"] = { 
        loop1 = { 
            Vector3.new(2168.750, 398.100, -534.732), 
            Vector3.new(2187.287, 397.600, -542.203), 
            Vector3.new(2200.867, 397.600, -532.074), 
            Vector3.new(2201.219, 398.100, -512.059), 
            Vector3.new(2174.893, 398.200, -512.526) 
        }, 
        loop2 = { 
            Vector3.new(2264.167, 397.600, -451.858), 
            Vector3.new(2264.311, 397.600, -423.763), 
            Vector3.new(2297.124, 397.600, -424.258), 
            Vector3.new(2296.829, 398.100, -452.198) 
        }, 
        loop3 = { 
            Vector3.new(2316.921, 405.900, -631.197), 
            Vector3.new(2312.305, 405.600, -609.797), 
            Vector3.new(2325.179, 399.600, -589.640), 
            Vector3.new(2362.215, 399.600, -601.585) 
        }, 
    },
}
